[theme]
primaryColor = "#8B5CF6"
backgroundColor = "#1a1a2e"
secondaryBackgroundColor = "#16213e"
textColor = "#ffffff"
font = "sans serif"

[server]
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = true
